### ISSUE TITLE
Ch. 2 Issue 

### ISSUE THREAD

**Issue by Jdavidson01** [jacobtnyoung/sna-textbook#7]
There were no grammatical or spacing issues in chapter 2. Just two recommendations:

1. Under "Learning Goals", the line that says "Be able to answer these questions:" could be deleted since there is no questions under it, only one statement.

2. Would it be possible for the words on the 2x3 table to be bigger because they seem a little small?

**Comment by jacobtnyoung** [comment]
Good suggestions. Will work on these. Thanks!
